# Generated by Django 5.2.5 on 2025-09-10 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('mod_approved', 'Mod Approved'), ('mod_rejected', 'Mod Rejected'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('game_created', 'Game Created'), ('category_created', 'Category Created'), ('page_created', 'Page Created'), ('other', 'Other Action')], max_length=20)),
                ('target_object', models.CharField(help_text='Description of what was acted upon', max_length=200)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending Review')], max_length=10)),
                ('review_notes', models.TextField(blank=True, help_text='Internal notes for review decision')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mods.mod')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
