# Generated by Django 5.2.5 on 2025-11-12 18:16

import mods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=mods.models.categoryBannerPath),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=mods.models.categoryIconPath),
        ),
        migrations.AddField(
            model_name='game',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=mods.models.gameBannerPath),
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=mods.models.gameIconPath),
        ),
    ]
